### ISSUE TITLE
Copy pasting from mobile device possible?

### ISSUE THREAD

**Issue by JustTheCoolest** [JustTheCoolest/VIT-Timetable-to-Calendar#5]

**Comment by harshadatta123** [comment]
![WhatsApp Image 2024-11-12 at 21 40 56_95bd6bf7](https://github.com/user-attachments/assets/ae657fe6-80cf-42e4-a751-3b14ac8712d2)

**Comment by JustTheCoolest** [comment]
Working if we open it as a desktop site
